//! `runseal :init [--force]` — validate the repo and install git hooks.
//!
//! Installs `.runseal/hooks/{pre-commit,commit-msg}` into the repo's hooks
//! directory. Existing hooks generated by a prior `:init` are replaced; foreign
//! hooks are left alone unless `--force` is given (then backed up first).

import { capture } from "@/lib/std/cmd.ts";
import { exists, join } from "@/lib/std/fs.ts";

const MARKER = "santi :init hook";
const HOOKS = ["pre-commit", "commit-msg"];
const REQUIRED_TOOLS = ["git", "deno", "cargo", "runseal"];
const REQUIRED_PATHS = [
  "runseal.toml",
  ".runseal/deno.json",
  ".runseal/hooks/pre-commit",
  ".runseal/hooks/commit-msg",
  ".runseal/wrappers/guard.ts",
];

export async function init(argv: string[]): Promise<number> {
  if (argv.includes("-h") || argv.includes("--help")) {
    usage();
    return 0;
  }
  const force = argv.includes("--force");
  const positional = argv.find((arg) => !arg.startsWith("-"));
  if (positional !== undefined) return fail(`unexpected argument: ${positional}`);

  console.log("==> resolving repository");
  const root = (await capture("git", ["rev-parse", "--show-toplevel"])).stdout.trim();
  if (root === "") return fail("not inside a git repository");
  const gitDir = (await capture("git", ["rev-parse", "--absolute-git-dir"])).stdout.trim();
  const hooksDir = join(gitDir, "hooks");
  console.log(`repository: ${root}`);

  console.log("==> checking required tools");
  for (const tool of REQUIRED_TOOLS) {
    if (!(await toolExists(tool))) return fail(`missing required tool: ${tool}`);
  }
  console.log(`ok: ${REQUIRED_TOOLS.join(", ")}`);

  console.log("==> checking repository entrypoints");
  for (const rel of REQUIRED_PATHS) {
    if (!exists(join(root, rel))) return fail(`missing required path: ${rel}`);
  }
  console.log("ok: repository entrypoints");

  console.log("==> installing git hooks");
  Deno.mkdirSync(hooksDir, { recursive: true });
  for (const name of HOOKS) {
    const dest = join(hooksDir, name);
    const prepared = prepareHook(dest, force);
    if (prepared !== 0) return prepared;
    Deno.copyFileSync(join(root, ".runseal/hooks", name), dest);
    chmod755(dest);
    console.log(`installed ${dest}`);
  }
  console.log("hooks installed — commits now refuse main and run `runseal :guard`");
  return 0;
}

function prepareHook(dest: string, force: boolean): number {
  if (!exists(dest)) return 0;
  let content = "";
  try {
    content = Deno.readTextFileSync(dest);
  } catch {
    content = "";
  }
  if (content.includes(MARKER)) return 0; // generated by us; safe to replace
  if (!force) {
    return fail(
      `${dest} exists and was not generated by :init — rerun with --force to back it up and replace it`,
    );
  }
  const backup = backupNumbered(dest);
  console.log(`backed up existing hook to ${backup}`);
  return 0;
}

function backupNumbered(path: string): string {
  let candidate = `${path}.bak`;
  let n = 1;
  while (exists(candidate)) candidate = `${path}.bak.${n++}`;
  Deno.renameSync(path, candidate);
  return candidate;
}

async function toolExists(tool: string): Promise<boolean> {
  const result = await capture("sh", ["-c", `command -v ${tool}`]);
  return result.code === 0 && result.stdout.trim() !== "";
}

function chmod755(path: string): void {
  try {
    Deno.chmodSync(path, 0o755);
  } catch {
    // non-unix platform; git uses its own executable handling
  }
}

function usage(): void {
  console.log("Usage: runseal :init [--force]");
  console.log("");
  console.log("Validate the repo and install git hooks (pre-commit, commit-msg).");
  console.log("  --force   back up a non-generated existing hook before replacing it");
}

function fail(message: string): number {
  console.error(`:init: ${message}`);
  return 1;
}
